# Generated by Django 3.2.6 on 2022-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='csv',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
