# Generated by Django 3.2.6 on 2022-02-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upload.email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.invoice'),
        ),
    ]
